### PR TITLE
Added timestamp feature

### LINKED ISSUE #2: Add timestamp to the profile
**Describe the feature you'd like**
Add the time of creation below the profile name as shown in the below image.

**Screenshots**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: open for all

### PR DESCRIPTION
**Pull request by Haid-Faiz**
Fixes #2 

Changes: [Added TimeStamp to profile ]

Screenshots for the change: 
Screenshot_20201005-120309_Quiet_Hours 1

### CODE REVIEW

**Comment by Haid-Faiz** [comment]
@rob729 i hope this PR will work now.... this time i created new repo & deleted that old messed up repo and now i made changes by keeping in mind of old mistakes.

**Comment by Haid-Faiz** [comment]
@rob729 but it is showing me conflicts in 3 files... what should i do to remove all these conflicts.

**Comment by rob729** [comment]
Did you merge the master code in your local codebase?
The merge conflict is arising because some new code has been merged into the master code and is not present in your PR's code.
You can read about merge conflicts and how to resolve them online.

**Comment by Haid-Faiz** [comment]
@rob729  oh.. i made a mistake.. i forked this repo from your initial repo but now your current repo is having new code merged in it. Means i need to fork your current master repo which is having new code changes in it by other participant... Right...?? then i need to perform changes & then it won't show me conflicts...  Am i correct..??

**Comment by rob729** [comment]
That can be a way of fixing this issue but not the recommended way.
As suggested earlier, read about merge conflicts as you can fix the issue of the conflicting files in this PR itself.
The main idea of resolving a merge conflict is to accept both the already existing code and the new code added by you.

**Comment by Haid-Faiz** [comment]
@rob729 i read about merge conflicts from here...  https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github
So, should i go with the process explained in it...??

**Comment by Haid-Faiz** [comment]
@rob729 still i am little confused... i attached the screenshot & in this particular case i need to keep both the changes done by me & other, Right...?? So, do i just need to remove this line binding.TxtImg.avatarBackgroundColor = bgColors[Random.nextInt(0, 8)]   Correct...??/

Screenshot (166)

**Comment by rob729** [comment]
Correct @Haid-Faiz.
Since it is the older implementation and is not used anymore so you will have to remove it.
Similarly, try doing on the other conflicting files.

**Comment by rob729** [comment]
Also, remember to remove the ">>>>master" and other similar lines from the code.

**Comment by Haid-Faiz** [comment]
@rob729 i resolved conflicts... I hope this will work now.

**Comment by rob729** [comment]
@Haid-Faiz Don't you think a migration policy would be required since a new variable has been added in Profile.kt?

**Comment by rob729** [comment]
Also, remember to squash your commits into a single commit.

**Comment by Haid-Faiz** [comment]
> @Haid-Faiz Don't you think a migration policy would be required since a new variable has been added in Profile.kt?

@rob729  What do i need to do this....??   
1.)  Like do i need to change version from 2 to 3... ?? 
2.)  In ProfileRoomDatabase.kt , Do i need to create one more variable of type Migration, like this....      
_______________________________________________________________________________________
             val MIGRATION_1_2: Migration = object : Migration(1, 2) {
             override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE profile_table " +
                        " ADD COLUMN colorIndex INTEGER NOT NULL DEFAULT 3")
            }
        }
______________________________________________________________________________________
with changes like...    

        val MIGRATION_2_3: Migration = object : Migration(2, 3) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE profile_table " +
                        " ADD COLUMN timeStamp STRING NOT NULL")
            }
        }

and including this change in addMigration() method-->    addMigrations(MIGRATION_1_2, MIGRATION_2_3)


Screenshot (167)

**Comment by rob729** [comment]
@Haid-Faiz There is already code related to migration present in the codebase. Just have a look at it and do the same for this PR.
Have a look at PR #12 to get some help.
You can always have a look at online resources when in doubt.

**Comment by Haid-Faiz** [comment]
@rob729  i added migration policy...  but Can we squash commits from android studio itself...??

**Comment by rob729** [comment]
Yes, you can squash commits from the android studio itself using the terminal present in the android studio.

**Comment by Haid-Faiz** [comment]
@rob729 Means we can use Android Studio Terminal as Git Bash...??

**Comment by rob729** [comment]
Yes.

**Comment by Haid-Faiz** [comment]
@rob729 i faced some confusion & difficulties in squashing the commits... but still i tried to squash them... Kindly check it & let me know if it is correct..

**Comment by rob729** [comment]
@Haid-Faiz I don't think you got the reason why I said to squash your commits.
The reason why I said to squash your commits into a single commit was that your PR has more than one commit and I only want one commit per PR.
I would suggest using the resources provided in the Gitter channel to learn how to squash commits.

**Comment by Haid-Faiz** [comment]
> @Haid-Faiz I don't think you got the reason why I said to squash your commits.
> The reason why I said to squash your commits into a single commit was that your PR has more than one commit and I only want one commit per PR.
> I would suggest using the resources provided in the Gitter channel to learn how to squash commits.

@rob729  ya i watched some tutorials about Squashing the commits.... i squashed them as described in the tutorials... so, have you  checked the commits..  I mean kindly let me know that what mistake i did.. like they are squashed successfully or not..?? 
& one more doubt.. Do i need to squash all the commits like commits done by you & other also or the commits just done by me...??

**Comment by rob729** [comment]
@Haid-Faiz Can you tell the current number of commits on this PR and what is the expected number of commits on a PR?

**Comment by Haid-Faiz** [comment]
@rob729 ok i got the point means it is showing 7 commits... means i need to squash these 7

**Comment by Haid-Faiz** [comment]
@rob729    i just again squashed them but on Git terminal it also shows different commits than on this PR... still i squashed them but here on this PR it is not showing squashed commits rather it is counting it... & making more commits here.... i confused

**Comment by rob729** [comment]
Can you share the screenshot of the commits shown while squashing them?

**Comment by Haid-Faiz** [comment]
> Can you share the screenshot of the commits shown while squashing them?

@rob729  but in this screenshot some commits are not there as i already squashed them...

Screenshot (168)

**Comment by rob729** [comment]
@Haid-Faiz I would suggest you watch that video again as I am not able to understand what you have done.
Just keep in mind that after you done with changes and merging the master branch only one commit should be there. So you should select the commits accordingly. You should know the last commit before you started making changes to the repo and should not include it in the squashing process.

**Comment by Haid-Faiz** [comment]
@rob729 ok thanks.... But can i again close this PR & generate new one because again i messed it up and i put too much time in solving problem of squashing.... kindly allow me to generate new PR...

**Comment by rob729** [comment]
Okay @Haid-Faiz you can open a new PR again.
Although keep in mind that I highly discourage the closing of a PR on which so much review has already been done.
Don't repeat these mistakes in the future.

**Comment by Haid-Faiz** [comment]
> Okay @Haid-Faiz you can open a new PR again.
> Although keep in mind that I highly discourage the closing of a PR on which so much review has already been done.
> Don't repeat these mistakes in the future.

Ok.. sorry for that.. & thanks for allowing me

**Comment by Haid-Faiz** [comment]
@rob729   Next time i need to do the following....

- firstly clone current master branch of your repo.
- then add all the changes (should i create new branch for my work...?? or should i continue with master)
- then commit the changes ( by this only one commit will there... Right...???)
- then create PR

**Comment by rob729** [comment]
You either make changes to master or create a new branch. Does not matter at this moment.
After making changes, commit them and if a new PR is merged into the master repo then merge the master repo into your local database.

**Comment by rob729** [comment]
When you merge the master code, then there will be two commits. So follow the git squash tutorial.

**Pull request closed without merging**
