### PR TITLE
Added current Timestamp to Profile

### LINKED ISSUE #2: Add timestamp to the profile
**Describe the feature you'd like**
Add the time of creation below the profile name as shown in the below image.

**Screenshots**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: open for all

### PR DESCRIPTION
**Pull request by Anshul1507**
Fixes #2 

Changes: Modify structure of cardview and adding getCurrentTime function in NewProfileFragment to fetch current timestamp and passed that through the binding  

NOTE: Uninstall previous version of current app from device and then try.

Screenshots for the change:

### CODE REVIEW

**Review by rob729 — CHANGES_REQUESTED** [review]
Why is there a need to uninstall the app?
Try to search online for a solution regarding this problem so that the user does not have to uninstall the app and the new features get updated on the existing app.  
Hint: Learn about migration in Room Database.

**Comment by Anshul1507** [comment]
Ok, I will learn regarding same, Thanks for the hint

**Comment by Anshul1507** [comment]
I am raising this concern of uninstalling because till now we hadn't save timestamp of tasks and in this fixes, i add one more key-pair in room db named of timestamp, so only new created task after this fixes will only shows creation time not all.

**Comment by rob729** [comment]
@Anshul1507 As I have mentioned in the above comment learn about migration in Room Database.
The need for uninstalling should not be there. 
Also, think about a real-life use case where the users who have already installed your app get an app update and you as a developer ask them to uninstall your app and then install again. Is it a good practice?

**Comment by Anshul1507** [comment]
Tell me one thing please, are you storing timestamp from the first version of your app?

**Comment by rob729** [comment]
No.

**Comment by Anshul1507** [comment]
Then how can we show up timestamp feature for that tasks.
From uninstalling of app related to showing up current feature of timestamp for newly created task for this version of app.

**Comment by Anshul1507** [comment]
Else if user update app before this feature, timestamp feature wont be shown for previous created task(only for new ones).

**Comment by rob729** [comment]
You can either show blank space at timestamp position for those profiles which have no timestamp or you can delete all the existing profiles (Destructive migration).

**Comment by Anshul1507** [comment]
if you install this version over prev, then blank space is already there.

**Comment by rob729** [comment]
What is the use of blank space if am doing a fresh install as the existing database will be deleted and every profile made after fresh install should have timestamp?

**Comment by Anshul1507** [comment]
Blank Space are for those who added hours before this version, Please clarify what you want to implement?

**Comment by rob729** [comment]
You wrote in PR description to uninstall previous version of current app from device and then try. So after uninstalling the app the database of the previous version of the app will be also deleted. So what is the purpose of the blank space then as in the new version of the app every profile should have timestamp?

**Comment by Anshul1507** [comment]
Blank space are for that situation when user update his app, prev tasks shows blank space and new tasks shows timestamp.

**Comment by rob729** [comment]
@Anshul1507 Can you tell me that if your device has quiet hours already installed and you install the new version of the app using the android studio then is the app crashing?
If yes then the update of the app from the play store will also crash.

**Comment by Anshul1507** [comment]
It is not crashing, try to install my version!

**Pull request closed without merging**
