### PR TITLE
Shifted Vibrate mode Switch

### LINKED ISSUE #22: Add Silent/Vibrate mode selector
**Describe the feature you'd like**
Currently, the app has a Silent/Vibrate mode selector in the settings option. It needs to be shifted to NewProfileFragment to allow users to select the mode individually for each profile.
Detail fragment should show the mode selected by the user.
Keep the default value to vibrate.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

### PR DESCRIPTION
**Pull request by coder2699**
Fixes #22 

Changes: 
1. Shifted Vibrate/Silent Mode Switch from settings to NewProfileFragment.
2. DetailsFragment displays the selected mode for individual profile.
3. Removed Vibrate Mode Switch from Settings

Screenshots for the change:

Vibration Mode OFF:

<table>
        <tr>
<td></td>
<td></td>
 </tr>
</table>        

Vibration Mode ON:

<table>
        <tr>
<td></td>
<td></td>
 </tr>
</table>

Landscape Mode

### CODE REVIEW

**Review by rob729 — CHANGES_REQUESTED** [review]
Please use the vibration.png for silent mode and an image similar to the below image for vibrate mode.
scrnli_10_10_2020_18-59-16
Also, display this image on the right of the profile name in the details fragment.
Change "Vibration" to "Vibrate" in newProfileFragment when in a selected state and "Silent" in an unselected state.
Also, increase the text size.

**Comment by coder2699** [comment]
Vibration Mode ON:

<table>
        <tr>
<td></td>
<td></td>
 </tr>
</table>        

Vibration Mode OFF:

<table>
        <tr>
<td></td>
<td></td>
 </tr>
</table>

Shall I push the code for these changes?

**Review by rob729 — CHANGES_REQUESTED** [review]
Reduce the distance between the profile name and vibrate icon by half.
Also, Increase the distance between the text and vibrate toggle

**Comment by coder2699** [comment]
> Reduce the distance between the profile name and vibrate icon by half.
> Also, Increase the distance between the text and vibrate toggle

Okay

**Comment by coder2699** [comment]
1). The distance between icon and profile name reduced to half
2). Distance between Switch and text increased

<table>
        <tr>
<td></td>
<td></td>
 </tr>
</table>

**Comment by rob729** [comment]
@coder2699 Have you tested the app whether it is working as expected? I am talking about the vibrate and silent mode.

**Comment by coder2699** [comment]
> @coder2699 Have you tested the app whether it is working as expected? I am talking about the vibrate and silent mode.

Yes. It is working fine except one thing that I want to highlight.
When silent mode is on, phone is still vibrating. I tried using the app from play store and in that also on silent mode, it is vibrating.
I think the RINGTONE_MODE_SILENCE has some problems with the newer versions, even in the original file it wasn't working.

**Comment by coder2699** [comment]
Since the issue was for shifting, so I didn't look for it more. But yes, this problem was coming, even in the original file.

**Comment by coder2699** [comment]
It is working on emulator though

**Comment by coder2699** [comment]
I am working to fix it.

**Comment by rob729** [comment]
@coder2699 If the issue of silent mode was already existing then you can create a new issue else you will have to fix it in this one.

**Comment by coder2699** [comment]
> @coder2699 If the issue of silent mode was already existing then you can create a new issue else you will have to fix it in this one.

@rob729 Yes, the issue was pre existing. But, I am just trying one thing. If it gets fixed then it's fine, otherwise I'll raise a new issue.

**Comment by rob729** [comment]
Okay

**Comment by rob729** [comment]
BTW I also tried the play store version of the app and it is working fine for me.

**Comment by coder2699** [comment]
> BTW I also tried the play store version of the app and it is working fine for me.

Okay then, once I push the new code I would request you to test it once on your device also. Maybe the problem is due to device and not the app.

**Comment by rob729** [comment]
BTW what are the changes made in the last commit?

**Comment by coder2699** [comment]
@rob729 I tried now. It is working fine on my emulator but not on my device. I think there's some problem with my device. But I think the app shall work fine.

**Comment by coder2699** [comment]
> BTW what are the changes made in the last commit?

This line was missing  in the earlier code in NewProfileFragment ".setInputData(vibData)"

**Comment by coder2699** [comment]
I also tried to replace RINGTONE_MODE_SILENCE with 0, but the problem wasn't resolved so I did not commit that.

**Review by rob729 — APPROVED** [review]

**Comment by rob729** [comment]
give @coder2699 25 points

**Pull request merged**
