### PR TITLE
fixed UI bugs

### LINKED ISSUE #53: Fix UI Bugs
,**Describe the bug**
<ul>
<li>The Avtar icon is not centrally placed and does not looks nice when profile name is of multiple lines. Fix it.</li>

<li>When profile name is of multiple lines, the vibrator icon and Repeat Weekly icon doesn't appear. Change the position of these icons in Details fragment after discussing it with @rob729 .</li>

<li>The color of  vibrator and silent icon is completely different from rest of the color scheme, which doesn't looks good. Change color of vibrator and silent icon to accent color.</li>

</ul>

**Would you like to work on the issue?**
-  Yes

### PR DESCRIPTION
**Pull request by coder2699**
Fixes #53 

Screenshots for the change:

### CODE REVIEW

**Review by rob729 — CHANGES_REQUESTED** [review]
Details fragment not as expected in landscape mode. Fix it.

**Comment by coder2699** [comment]
@rob729 Can you elaborate what needs to be fixed? When I checked the details fragment is shown like this:

**Comment by coder2699** [comment]
@rob729  I think due to increasing number of items the height of bottom sheet is increasing. So i will reduce the margin gaps for some views in details fragment. That will reduce its height

**Comment by rob729** [comment]
Reduce the margins slightly. Also, make the whole layout scrollable.

**Pull request closed without merging**
