### PR TITLE
Updated Readme.md

### LINKED ISSUE #64: Update Screenshots in Readme.md
**Describe the chore**
A decent number of bug fixes and features have been added since so time to update the screenshots in the readme file.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

### PR DESCRIPTION
**Pull request by coder2699**
Fixes #64

### CODE REVIEW

**Comment by rob729** [comment]
@coder2699 Can you use the earlier device which was used last time for the screenshots?
It was looking better on that device.

**Comment by coder2699** [comment]
> @coder2699 Can you use the earlier device which was used last time for the screenshots?
> It was looking better on that device.

@rob729 That was my emulator, I will take ss on it an upload. On my emulator screen recording is not working properly, so the 1st gif image will remain like that. Will it be ok?

**Comment by rob729** [comment]
@coder2699 You take the screenshots. I will give you the GIF.

**Comment by coder2699** [comment]
@rob729 Thanks

**Comment by coder2699** [comment]
@rob729 I have updated the screenshots

**Review by rob729 — APPROVED** [review]

**Comment by rob729** [comment]
give @coder2699 5 points

**Pull request merged**
